USER_CREDENTIALS_FILEPATH = "user_credentials.ini"
TEMP_DIR_NAME = "temp"
OUPUT_DATA_DIR_NAME = "OUTPUT"
FOLLOWED_COUNT_FILE = "followed_count.json"
FOLLOWED_COUNT_PATH = f'{TEMP_DIR_NAME}/{FOLLOWED_COUNT_FILE}'
FOLLOW_LIMIT = 200